language: node_js
node_js:
  - "lts/*"
cache: yarn
branches:
  only:
  - master
script:
  - yarn lint:js
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: docs
  on:
    branch: master
